---
steps:

  - name: gcr.io/cloud-builders/docker
    args: [ "build", "-t", "gcr.io/$PROJECT_ID/backend:$SHORT_SHA", "." ]
  
  - name: gcr.io/cloud-builders/docker
    args: [ "push", "gcr.io/$PROJECT_ID/backend:$SHORT_SHA" ]
  
  - name: busybox
    args: [ "sed", "-i", "s/latest/$SHORT_SHA/g", "k8s/deployment.yaml" ]

  - name: gcr.io/cloud-builders/gcloud
    args: [ "container", "clusters", "get-credentials", "teatime-cluster", "--region", "europe-west3" ]

  - name: gcr.io/cloud-builders/gcloud
    entrypoint: "kubectl"
    args: [ "apply", "-f", "k8s/" ]

