---
steps:
 
  # Build docker image
  - name: gcr.io/cloud-builders/docker
    args: [ "build", "-t", "gcr.io/$PROJECT_ID/backend:$SHORT_SHA", "." ]
  
  # Push docker image to GCR
  - name: gcr.io/cloud-builders/docker
    args: [ "push", "gcr.io/$PROJECT_ID/backend:$SHORT_SHA" ]
  
  # Set image tag (Git SHA) in k8s deployment
  - name: busybox
    args: [ "sed", "-i", "s/latest/$SHORT_SHA/g", "k8s/deployment.yaml" ]

  # Configure kubectl to talk to our cluster
  - name: gcr.io/cloud-builders/gcloud
    args: [ "container", "clusters", "get-credentials", "$_CLUSTER", "--region", "europe-west3" ]

  # Configure deployment with new image tag
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: "kubectl"
    args: [ "apply", "-f", "k8s/" ]

