---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tea
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gcr.io/vincit-teatime/backend:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            periodSeconds: 5
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            periodSeconds: 5
            initialDelaySeconds: 10
            timeoutSeconds: 3
          env:
            - name: _JAVA_OPTIONS
              value: -Xss256K -Xmx192M -Xms64M -XX:MaxRAM=256M -XX:MaxMetaspaceSize=64M

